// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: vexxvakan/sidecar/v1/drand_control.proto

package sidecarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DrandControl_Status_FullMethodName = "/vexxvakan.sidecar.v1.DrandControl/Status"
	DrandControl_Start_FullMethodName  = "/vexxvakan.sidecar.v1.DrandControl/Start"
	DrandControl_Stop_FullMethodName   = "/vexxvakan.sidecar.v1.DrandControl/Stop"
	DrandControl_Logs_FullMethodName   = "/vexxvakan.sidecar.v1.DrandControl/Logs"
)

// DrandControlClient is the client API for DrandControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DrandControl defines a gRPC control plane for a supervised drand subprocess.
type DrandControlClient interface {
	// Status returns the current supervision state for drand.
	Status(ctx context.Context, in *DrandStatusRequest, opts ...grpc.CallOption) (*DrandStatusResponse, error)
	// Start starts the supervised drand subprocess.
	Start(ctx context.Context, in *DrandStartRequest, opts ...grpc.CallOption) (*DrandStartResponse, error)
	// Stop stops the supervised drand subprocess.
	Stop(ctx context.Context, in *DrandStopRequest, opts ...grpc.CallOption) (*DrandStopResponse, error)
	// Logs returns recent log entries from the supervised drand subprocess.
	Logs(ctx context.Context, in *DrandLogsRequest, opts ...grpc.CallOption) (*DrandLogsResponse, error)
}

type drandControlClient struct {
	cc grpc.ClientConnInterface
}

func NewDrandControlClient(cc grpc.ClientConnInterface) DrandControlClient {
	return &drandControlClient{cc}
}

func (c *drandControlClient) Status(ctx context.Context, in *DrandStatusRequest, opts ...grpc.CallOption) (*DrandStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrandStatusResponse)
	err := c.cc.Invoke(ctx, DrandControl_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drandControlClient) Start(ctx context.Context, in *DrandStartRequest, opts ...grpc.CallOption) (*DrandStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrandStartResponse)
	err := c.cc.Invoke(ctx, DrandControl_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drandControlClient) Stop(ctx context.Context, in *DrandStopRequest, opts ...grpc.CallOption) (*DrandStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrandStopResponse)
	err := c.cc.Invoke(ctx, DrandControl_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drandControlClient) Logs(ctx context.Context, in *DrandLogsRequest, opts ...grpc.CallOption) (*DrandLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrandLogsResponse)
	err := c.cc.Invoke(ctx, DrandControl_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrandControlServer is the server API for DrandControl service.
// All implementations must embed UnimplementedDrandControlServer
// for forward compatibility.
//
// DrandControl defines a gRPC control plane for a supervised drand subprocess.
type DrandControlServer interface {
	// Status returns the current supervision state for drand.
	Status(context.Context, *DrandStatusRequest) (*DrandStatusResponse, error)
	// Start starts the supervised drand subprocess.
	Start(context.Context, *DrandStartRequest) (*DrandStartResponse, error)
	// Stop stops the supervised drand subprocess.
	Stop(context.Context, *DrandStopRequest) (*DrandStopResponse, error)
	// Logs returns recent log entries from the supervised drand subprocess.
	Logs(context.Context, *DrandLogsRequest) (*DrandLogsResponse, error)
	mustEmbedUnimplementedDrandControlServer()
}

// UnimplementedDrandControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDrandControlServer struct{}

func (UnimplementedDrandControlServer) Status(context.Context, *DrandStatusRequest) (*DrandStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDrandControlServer) Start(context.Context, *DrandStartRequest) (*DrandStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedDrandControlServer) Stop(context.Context, *DrandStopRequest) (*DrandStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedDrandControlServer) Logs(context.Context, *DrandLogsRequest) (*DrandLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedDrandControlServer) mustEmbedUnimplementedDrandControlServer() {}
func (UnimplementedDrandControlServer) testEmbeddedByValue()                      {}

// UnsafeDrandControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrandControlServer will
// result in compilation errors.
type UnsafeDrandControlServer interface {
	mustEmbedUnimplementedDrandControlServer()
}

func RegisterDrandControlServer(s grpc.ServiceRegistrar, srv DrandControlServer) {
	// If the following call panics, it indicates UnimplementedDrandControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DrandControl_ServiceDesc, srv)
}

func _DrandControl_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrandStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrandControlServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrandControl_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrandControlServer).Status(ctx, req.(*DrandStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrandControl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrandStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrandControlServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrandControl_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrandControlServer).Start(ctx, req.(*DrandStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrandControl_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrandStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrandControlServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrandControl_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrandControlServer).Stop(ctx, req.(*DrandStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrandControl_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrandLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrandControlServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrandControl_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrandControlServer).Logs(ctx, req.(*DrandLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DrandControl_ServiceDesc is the grpc.ServiceDesc for DrandControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DrandControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vexxvakan.sidecar.v1.DrandControl",
	HandlerType: (*DrandControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _DrandControl_Status_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _DrandControl_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _DrandControl_Stop_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _DrandControl_Logs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vexxvakan/sidecar/v1/drand_control.proto",
}
