services:
  serena:
    container_name: ${SERENA_CONTAINER_NAME:-serena}
    image: ${SERENA_IMAGE:-ghcr.io/oraios/serena:latest}
    volumes:
      # Give the container access to the directory where Codex was launched.
      - ${SERENA_HOST_PWD}:${SERENA_HOST_PWD}
      # Persist Serena config/logs into the project-local `.serena/` directory.
      - ${SERENA_HOST_CONFIG_DIR}:/workspaces/serena/config
    ports:
      - "${SERENA_PORT:-9121}:9121" # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282" # Dashboard port
    environment:
      - TZ=${TZ:-UTC}
      - SERENA_DOCKER=1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "code=$$(curl -s -o /dev/null -w '%{http_code}' --max-time 2 -X POST -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' --data '{}' http://127.0.0.1:9121/mcp || echo 000); case \"$$code\" in 200|400|406) exit 0 ;; *) exit 1 ;; esac",
        ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
    restart: unless-stopped
    command:
      - serena-mcp-server
      - --transport
      - ${SERENA_TRANSPORT:-streamable-http}
      - --port
      - "9121"
      - --host
      - ${SERENA_BIND_HOST:-0.0.0.0}
      - --context
      - ${SERENA_CONTEXT:-codex}
      - --project
      - ${SERENA_HOST_PWD}
