// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package vrfv1

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_GenesisState_3_list)(nil)

type _GenesisState_3_list struct {
	list *[]*AllowlistEntry
}

func (x *_GenesisState_3_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_3_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_GenesisState_3_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*AllowlistEntry)
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_3_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*AllowlistEntry)
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_3_list) AppendMutable() protoreflect.Value {
	v := new(AllowlistEntry)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_3_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_3_list) NewElement() protoreflect.Value {
	v := new(AllowlistEntry)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_3_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_GenesisState_4_list)(nil)

type _GenesisState_4_list struct {
	list *[]*VrfIdentity
}

func (x *_GenesisState_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_GenesisState_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VrfIdentity)
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VrfIdentity)
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_4_list) AppendMutable() protoreflect.Value {
	v := new(VrfIdentity)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_4_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_4_list) NewElement() protoreflect.Value {
	v := new(VrfIdentity)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_4_list) IsValid() bool {
	return x.list != nil
}

var (
	md_GenesisState               protoreflect.MessageDescriptor
	fd_GenesisState_params        protoreflect.FieldDescriptor
	fd_GenesisState_latest_beacon protoreflect.FieldDescriptor
	fd_GenesisState_committee     protoreflect.FieldDescriptor
	fd_GenesisState_identities    protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_vrf_v1_genesis_proto_init()
	md_GenesisState = File_vexxvakan_vrf_v1_genesis_proto.Messages().ByName("GenesisState")
	fd_GenesisState_params = md_GenesisState.Fields().ByName("params")
	fd_GenesisState_latest_beacon = md_GenesisState.Fields().ByName("latest_beacon")
	fd_GenesisState_committee = md_GenesisState.Fields().ByName("committee")
	fd_GenesisState_identities = md_GenesisState.Fields().ByName("identities")
}

var _ protoreflect.Message = (*fastReflection_GenesisState)(nil)

type fastReflection_GenesisState GenesisState

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	return (*fastReflection_GenesisState)(x)
}

func (x *GenesisState) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_vrf_v1_genesis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_GenesisState_messageType fastReflection_GenesisState_messageType
var _ protoreflect.MessageType = fastReflection_GenesisState_messageType{}

type fastReflection_GenesisState_messageType struct{}

func (x fastReflection_GenesisState_messageType) Zero() protoreflect.Message {
	return (*fastReflection_GenesisState)(nil)
}
func (x fastReflection_GenesisState_messageType) New() protoreflect.Message {
	return new(fastReflection_GenesisState)
}
func (x fastReflection_GenesisState_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_GenesisState
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_GenesisState) Descriptor() protoreflect.MessageDescriptor {
	return md_GenesisState
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_GenesisState) Type() protoreflect.MessageType {
	return _fastReflection_GenesisState_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_GenesisState) New() protoreflect.Message {
	return new(fastReflection_GenesisState)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_GenesisState) Interface() protoreflect.ProtoMessage {
	return (*GenesisState)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_GenesisState) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Params != nil {
		value := protoreflect.ValueOfMessage(x.Params.ProtoReflect())
		if !f(fd_GenesisState_params, value) {
			return
		}
	}
	if x.LatestBeacon != nil {
		value := protoreflect.ValueOfMessage(x.LatestBeacon.ProtoReflect())
		if !f(fd_GenesisState_latest_beacon, value) {
			return
		}
	}
	if len(x.Committee) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_3_list{list: &x.Committee})
		if !f(fd_GenesisState_committee, value) {
			return
		}
	}
	if len(x.Identities) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_4_list{list: &x.Identities})
		if !f(fd_GenesisState_identities, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_GenesisState) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.GenesisState.params":
		return x.Params != nil
	case "vexxvakan.vrf.v1.GenesisState.latest_beacon":
		return x.LatestBeacon != nil
	case "vexxvakan.vrf.v1.GenesisState.committee":
		return len(x.Committee) != 0
	case "vexxvakan.vrf.v1.GenesisState.identities":
		return len(x.Identities) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.GenesisState"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.GenesisState.params":
		x.Params = nil
	case "vexxvakan.vrf.v1.GenesisState.latest_beacon":
		x.LatestBeacon = nil
	case "vexxvakan.vrf.v1.GenesisState.committee":
		x.Committee = nil
	case "vexxvakan.vrf.v1.GenesisState.identities":
		x.Identities = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.GenesisState"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_GenesisState) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.vrf.v1.GenesisState.params":
		value := x.Params
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "vexxvakan.vrf.v1.GenesisState.latest_beacon":
		value := x.LatestBeacon
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "vexxvakan.vrf.v1.GenesisState.committee":
		if len(x.Committee) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_3_list{})
		}
		listValue := &_GenesisState_3_list{list: &x.Committee}
		return protoreflect.ValueOfList(listValue)
	case "vexxvakan.vrf.v1.GenesisState.identities":
		if len(x.Identities) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_4_list{})
		}
		listValue := &_GenesisState_4_list{list: &x.Identities}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.GenesisState"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.GenesisState does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.GenesisState.params":
		x.Params = value.Message().Interface().(*VrfParams)
	case "vexxvakan.vrf.v1.GenesisState.latest_beacon":
		x.LatestBeacon = value.Message().Interface().(*VrfBeacon)
	case "vexxvakan.vrf.v1.GenesisState.committee":
		lv := value.List()
		clv := lv.(*_GenesisState_3_list)
		x.Committee = *clv.list
	case "vexxvakan.vrf.v1.GenesisState.identities":
		lv := value.List()
		clv := lv.(*_GenesisState_4_list)
		x.Identities = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.GenesisState"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.GenesisState.params":
		if x.Params == nil {
			x.Params = new(VrfParams)
		}
		return protoreflect.ValueOfMessage(x.Params.ProtoReflect())
	case "vexxvakan.vrf.v1.GenesisState.latest_beacon":
		if x.LatestBeacon == nil {
			x.LatestBeacon = new(VrfBeacon)
		}
		return protoreflect.ValueOfMessage(x.LatestBeacon.ProtoReflect())
	case "vexxvakan.vrf.v1.GenesisState.committee":
		if x.Committee == nil {
			x.Committee = []*AllowlistEntry{}
		}
		value := &_GenesisState_3_list{list: &x.Committee}
		return protoreflect.ValueOfList(value)
	case "vexxvakan.vrf.v1.GenesisState.identities":
		if x.Identities == nil {
			x.Identities = []*VrfIdentity{}
		}
		value := &_GenesisState_4_list{list: &x.Identities}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.GenesisState"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.GenesisState does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_GenesisState) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.GenesisState.params":
		m := new(VrfParams)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "vexxvakan.vrf.v1.GenesisState.latest_beacon":
		m := new(VrfBeacon)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "vexxvakan.vrf.v1.GenesisState.committee":
		list := []*AllowlistEntry{}
		return protoreflect.ValueOfList(&_GenesisState_3_list{list: &list})
	case "vexxvakan.vrf.v1.GenesisState.identities":
		list := []*VrfIdentity{}
		return protoreflect.ValueOfList(&_GenesisState_4_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.GenesisState"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.GenesisState does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_GenesisState) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.vrf.v1.GenesisState", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_GenesisState) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_GenesisState) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_GenesisState) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Params != nil {
			l = options.Size(x.Params)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.LatestBeacon != nil {
			l = options.Size(x.LatestBeacon)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Committee) > 0 {
			for _, e := range x.Committee {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Identities) > 0 {
			for _, e := range x.Identities {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Identities) > 0 {
			for iNdEx := len(x.Identities) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Identities[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x22
			}
		}
		if len(x.Committee) > 0 {
			for iNdEx := len(x.Committee) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Committee[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x1a
			}
		}
		if x.LatestBeacon != nil {
			encoded, err := options.Marshal(x.LatestBeacon)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x12
		}
		if x.Params != nil {
			encoded, err := options.Marshal(x.Params)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Params == nil {
					x.Params = &VrfParams{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Params); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LatestBeacon", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.LatestBeacon == nil {
					x.LatestBeacon = &VrfBeacon{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.LatestBeacon); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Committee", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Committee = append(x.Committee, &AllowlistEntry{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Committee[len(x.Committee)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Identities", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Identities = append(x.Identities, &VrfIdentity{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Identities[len(x.Identities)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_VrfParams                       protoreflect.MessageDescriptor
	fd_VrfParams_chain_hash            protoreflect.FieldDescriptor
	fd_VrfParams_public_key            protoreflect.FieldDescriptor
	fd_VrfParams_period_seconds        protoreflect.FieldDescriptor
	fd_VrfParams_genesis_unix_sec      protoreflect.FieldDescriptor
	fd_VrfParams_safety_margin_seconds protoreflect.FieldDescriptor
	fd_VrfParams_enabled               protoreflect.FieldDescriptor
	fd_VrfParams_reshare_epoch         protoreflect.FieldDescriptor
	fd_VrfParams_slashing_grace_blocks protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_vrf_v1_genesis_proto_init()
	md_VrfParams = File_vexxvakan_vrf_v1_genesis_proto.Messages().ByName("VrfParams")
	fd_VrfParams_chain_hash = md_VrfParams.Fields().ByName("chain_hash")
	fd_VrfParams_public_key = md_VrfParams.Fields().ByName("public_key")
	fd_VrfParams_period_seconds = md_VrfParams.Fields().ByName("period_seconds")
	fd_VrfParams_genesis_unix_sec = md_VrfParams.Fields().ByName("genesis_unix_sec")
	fd_VrfParams_safety_margin_seconds = md_VrfParams.Fields().ByName("safety_margin_seconds")
	fd_VrfParams_enabled = md_VrfParams.Fields().ByName("enabled")
	fd_VrfParams_reshare_epoch = md_VrfParams.Fields().ByName("reshare_epoch")
	fd_VrfParams_slashing_grace_blocks = md_VrfParams.Fields().ByName("slashing_grace_blocks")
}

var _ protoreflect.Message = (*fastReflection_VrfParams)(nil)

type fastReflection_VrfParams VrfParams

func (x *VrfParams) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VrfParams)(x)
}

func (x *VrfParams) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_vrf_v1_genesis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VrfParams_messageType fastReflection_VrfParams_messageType
var _ protoreflect.MessageType = fastReflection_VrfParams_messageType{}

type fastReflection_VrfParams_messageType struct{}

func (x fastReflection_VrfParams_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VrfParams)(nil)
}
func (x fastReflection_VrfParams_messageType) New() protoreflect.Message {
	return new(fastReflection_VrfParams)
}
func (x fastReflection_VrfParams_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfParams
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VrfParams) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfParams
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VrfParams) Type() protoreflect.MessageType {
	return _fastReflection_VrfParams_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VrfParams) New() protoreflect.Message {
	return new(fastReflection_VrfParams)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VrfParams) Interface() protoreflect.ProtoMessage {
	return (*VrfParams)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VrfParams) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.ChainHash) != 0 {
		value := protoreflect.ValueOfBytes(x.ChainHash)
		if !f(fd_VrfParams_chain_hash, value) {
			return
		}
	}
	if len(x.PublicKey) != 0 {
		value := protoreflect.ValueOfBytes(x.PublicKey)
		if !f(fd_VrfParams_public_key, value) {
			return
		}
	}
	if x.PeriodSeconds != uint64(0) {
		value := protoreflect.ValueOfUint64(x.PeriodSeconds)
		if !f(fd_VrfParams_period_seconds, value) {
			return
		}
	}
	if x.GenesisUnixSec != int64(0) {
		value := protoreflect.ValueOfInt64(x.GenesisUnixSec)
		if !f(fd_VrfParams_genesis_unix_sec, value) {
			return
		}
	}
	if x.SafetyMarginSeconds != uint64(0) {
		value := protoreflect.ValueOfUint64(x.SafetyMarginSeconds)
		if !f(fd_VrfParams_safety_margin_seconds, value) {
			return
		}
	}
	if x.Enabled != false {
		value := protoreflect.ValueOfBool(x.Enabled)
		if !f(fd_VrfParams_enabled, value) {
			return
		}
	}
	if x.ReshareEpoch != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ReshareEpoch)
		if !f(fd_VrfParams_reshare_epoch, value) {
			return
		}
	}
	if x.SlashingGraceBlocks != uint64(0) {
		value := protoreflect.ValueOfUint64(x.SlashingGraceBlocks)
		if !f(fd_VrfParams_slashing_grace_blocks, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VrfParams) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfParams.chain_hash":
		return len(x.ChainHash) != 0
	case "vexxvakan.vrf.v1.VrfParams.public_key":
		return len(x.PublicKey) != 0
	case "vexxvakan.vrf.v1.VrfParams.period_seconds":
		return x.PeriodSeconds != uint64(0)
	case "vexxvakan.vrf.v1.VrfParams.genesis_unix_sec":
		return x.GenesisUnixSec != int64(0)
	case "vexxvakan.vrf.v1.VrfParams.safety_margin_seconds":
		return x.SafetyMarginSeconds != uint64(0)
	case "vexxvakan.vrf.v1.VrfParams.enabled":
		return x.Enabled != false
	case "vexxvakan.vrf.v1.VrfParams.reshare_epoch":
		return x.ReshareEpoch != uint64(0)
	case "vexxvakan.vrf.v1.VrfParams.slashing_grace_blocks":
		return x.SlashingGraceBlocks != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfParams"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfParams does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfParams) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfParams.chain_hash":
		x.ChainHash = nil
	case "vexxvakan.vrf.v1.VrfParams.public_key":
		x.PublicKey = nil
	case "vexxvakan.vrf.v1.VrfParams.period_seconds":
		x.PeriodSeconds = uint64(0)
	case "vexxvakan.vrf.v1.VrfParams.genesis_unix_sec":
		x.GenesisUnixSec = int64(0)
	case "vexxvakan.vrf.v1.VrfParams.safety_margin_seconds":
		x.SafetyMarginSeconds = uint64(0)
	case "vexxvakan.vrf.v1.VrfParams.enabled":
		x.Enabled = false
	case "vexxvakan.vrf.v1.VrfParams.reshare_epoch":
		x.ReshareEpoch = uint64(0)
	case "vexxvakan.vrf.v1.VrfParams.slashing_grace_blocks":
		x.SlashingGraceBlocks = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfParams"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfParams does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VrfParams) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.vrf.v1.VrfParams.chain_hash":
		value := x.ChainHash
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.v1.VrfParams.public_key":
		value := x.PublicKey
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.v1.VrfParams.period_seconds":
		value := x.PeriodSeconds
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.vrf.v1.VrfParams.genesis_unix_sec":
		value := x.GenesisUnixSec
		return protoreflect.ValueOfInt64(value)
	case "vexxvakan.vrf.v1.VrfParams.safety_margin_seconds":
		value := x.SafetyMarginSeconds
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.vrf.v1.VrfParams.enabled":
		value := x.Enabled
		return protoreflect.ValueOfBool(value)
	case "vexxvakan.vrf.v1.VrfParams.reshare_epoch":
		value := x.ReshareEpoch
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.vrf.v1.VrfParams.slashing_grace_blocks":
		value := x.SlashingGraceBlocks
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfParams"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfParams does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfParams) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfParams.chain_hash":
		x.ChainHash = value.Bytes()
	case "vexxvakan.vrf.v1.VrfParams.public_key":
		x.PublicKey = value.Bytes()
	case "vexxvakan.vrf.v1.VrfParams.period_seconds":
		x.PeriodSeconds = value.Uint()
	case "vexxvakan.vrf.v1.VrfParams.genesis_unix_sec":
		x.GenesisUnixSec = value.Int()
	case "vexxvakan.vrf.v1.VrfParams.safety_margin_seconds":
		x.SafetyMarginSeconds = value.Uint()
	case "vexxvakan.vrf.v1.VrfParams.enabled":
		x.Enabled = value.Bool()
	case "vexxvakan.vrf.v1.VrfParams.reshare_epoch":
		x.ReshareEpoch = value.Uint()
	case "vexxvakan.vrf.v1.VrfParams.slashing_grace_blocks":
		x.SlashingGraceBlocks = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfParams"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfParams does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfParams) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfParams.chain_hash":
		panic(fmt.Errorf("field chain_hash of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.public_key":
		panic(fmt.Errorf("field public_key of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.period_seconds":
		panic(fmt.Errorf("field period_seconds of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.genesis_unix_sec":
		panic(fmt.Errorf("field genesis_unix_sec of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.safety_margin_seconds":
		panic(fmt.Errorf("field safety_margin_seconds of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.enabled":
		panic(fmt.Errorf("field enabled of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.reshare_epoch":
		panic(fmt.Errorf("field reshare_epoch of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	case "vexxvakan.vrf.v1.VrfParams.slashing_grace_blocks":
		panic(fmt.Errorf("field slashing_grace_blocks of message vexxvakan.vrf.v1.VrfParams is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfParams"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfParams does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VrfParams) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfParams.chain_hash":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.v1.VrfParams.public_key":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.v1.VrfParams.period_seconds":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.vrf.v1.VrfParams.genesis_unix_sec":
		return protoreflect.ValueOfInt64(int64(0))
	case "vexxvakan.vrf.v1.VrfParams.safety_margin_seconds":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.vrf.v1.VrfParams.enabled":
		return protoreflect.ValueOfBool(false)
	case "vexxvakan.vrf.v1.VrfParams.reshare_epoch":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.vrf.v1.VrfParams.slashing_grace_blocks":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfParams"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfParams does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VrfParams) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.vrf.v1.VrfParams", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VrfParams) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfParams) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VrfParams) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VrfParams) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VrfParams)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.ChainHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PublicKey)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.PeriodSeconds != 0 {
			n += 1 + runtime.Sov(uint64(x.PeriodSeconds))
		}
		if x.GenesisUnixSec != 0 {
			n += 1 + runtime.Sov(uint64(x.GenesisUnixSec))
		}
		if x.SafetyMarginSeconds != 0 {
			n += 1 + runtime.Sov(uint64(x.SafetyMarginSeconds))
		}
		if x.Enabled {
			n += 2
		}
		if x.ReshareEpoch != 0 {
			n += 1 + runtime.Sov(uint64(x.ReshareEpoch))
		}
		if x.SlashingGraceBlocks != 0 {
			n += 1 + runtime.Sov(uint64(x.SlashingGraceBlocks))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VrfParams)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.SlashingGraceBlocks != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SlashingGraceBlocks))
			i--
			dAtA[i] = 0x40
		}
		if x.ReshareEpoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ReshareEpoch))
			i--
			dAtA[i] = 0x38
		}
		if x.Enabled {
			i--
			if x.Enabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x30
		}
		if x.SafetyMarginSeconds != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SafetyMarginSeconds))
			i--
			dAtA[i] = 0x28
		}
		if x.GenesisUnixSec != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.GenesisUnixSec))
			i--
			dAtA[i] = 0x20
		}
		if x.PeriodSeconds != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PeriodSeconds))
			i--
			dAtA[i] = 0x18
		}
		if len(x.PublicKey) > 0 {
			i -= len(x.PublicKey)
			copy(dAtA[i:], x.PublicKey)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PublicKey)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.ChainHash) > 0 {
			i -= len(x.ChainHash)
			copy(dAtA[i:], x.ChainHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ChainHash)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VrfParams)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfParams: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfParams: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ChainHash = append(x.ChainHash[:0], dAtA[iNdEx:postIndex]...)
				if x.ChainHash == nil {
					x.ChainHash = []byte{}
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PublicKey = append(x.PublicKey[:0], dAtA[iNdEx:postIndex]...)
				if x.PublicKey == nil {
					x.PublicKey = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PeriodSeconds", wireType)
				}
				x.PeriodSeconds = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PeriodSeconds |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GenesisUnixSec", wireType)
				}
				x.GenesisUnixSec = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.GenesisUnixSec |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SafetyMarginSeconds", wireType)
				}
				x.SafetyMarginSeconds = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SafetyMarginSeconds |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Enabled = bool(v != 0)
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ReshareEpoch", wireType)
				}
				x.ReshareEpoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ReshareEpoch |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SlashingGraceBlocks", wireType)
				}
				x.SlashingGraceBlocks = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SlashingGraceBlocks |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vexxvakan/vrf/v1/genesis.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the vrf module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// params defines the module parameters.
	Params *VrfParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// latest_beacon is the canonical drand beacon for the current height, if any.
	LatestBeacon *VrfBeacon `protobuf:"bytes,2,opt,name=latest_beacon,json=latestBeacon,proto3" json:"latest_beacon,omitempty"`
	// committee contains allowlisted authorities for VRF emergency disable and
	// resharing scheduling.
	Committee []*AllowlistEntry `protobuf:"bytes,3,rep,name=committee,proto3" json:"committee,omitempty"`
	// identities contains validator -> drand identity bindings.
	Identities []*VrfIdentity `protobuf:"bytes,4,rep,name=identities,proto3" json:"identities,omitempty"`
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_vrf_v1_genesis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_vexxvakan_vrf_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *VrfParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetLatestBeacon() *VrfBeacon {
	if x != nil {
		return x.LatestBeacon
	}
	return nil
}

func (x *GenesisState) GetCommittee() []*AllowlistEntry {
	if x != nil {
		return x.Committee
	}
	return nil
}

func (x *GenesisState) GetIdentities() []*VrfIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

// VrfParams mirrors the PRD definition and contains all cryptographic and timing
// context needed to verify drand beacons on-chain and map block time to drand
// rounds.
type VrfParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// chain_hash is the canonical identifier for the drand chain.
	ChainHash []byte `protobuf:"bytes,1,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// public_key is the collective BLS public key for the drand group.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// period_seconds is the drand beacon period in seconds.
	PeriodSeconds uint64 `protobuf:"varint,3,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// genesis_unix_sec is the drand genesis time (UNIX seconds) for round 1.
	GenesisUnixSec int64 `protobuf:"varint,4,opt,name=genesis_unix_sec,json=genesisUnixSec,proto3" json:"genesis_unix_sec,omitempty"`
	// safety_margin_seconds is the safety margin applied when computing
	// target_round(H) from block times.
	SafetyMarginSeconds uint64 `protobuf:"varint,5,opt,name=safety_margin_seconds,json=safetyMarginSeconds,proto3" json:"safety_margin_seconds,omitempty"`
	// enabled gates VRF behavior in ExtendVote/PreBlock.
	Enabled bool `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// reshare_epoch is the on-chain resharing signal / epoch counter.
	ReshareEpoch uint64 `protobuf:"varint,7,opt,name=reshare_epoch,json=reshareEpoch,proto3" json:"reshare_epoch,omitempty"`
	// slashing_grace_blocks configures the slashing grace window.
	SlashingGraceBlocks uint64 `protobuf:"varint,8,opt,name=slashing_grace_blocks,json=slashingGraceBlocks,proto3" json:"slashing_grace_blocks,omitempty"`
}

func (x *VrfParams) Reset() {
	*x = VrfParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_vrf_v1_genesis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfParams) ProtoMessage() {}

// Deprecated: Use VrfParams.ProtoReflect.Descriptor instead.
func (*VrfParams) Descriptor() ([]byte, []int) {
	return file_vexxvakan_vrf_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *VrfParams) GetChainHash() []byte {
	if x != nil {
		return x.ChainHash
	}
	return nil
}

func (x *VrfParams) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *VrfParams) GetPeriodSeconds() uint64 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *VrfParams) GetGenesisUnixSec() int64 {
	if x != nil {
		return x.GenesisUnixSec
	}
	return 0
}

func (x *VrfParams) GetSafetyMarginSeconds() uint64 {
	if x != nil {
		return x.SafetyMarginSeconds
	}
	return 0
}

func (x *VrfParams) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *VrfParams) GetReshareEpoch() uint64 {
	if x != nil {
		return x.ReshareEpoch
	}
	return 0
}

func (x *VrfParams) GetSlashingGraceBlocks() uint64 {
	if x != nil {
		return x.SlashingGraceBlocks
	}
	return 0
}

var File_vexxvakan_vrf_v1_genesis_proto protoreflect.FileDescriptor

var file_vexxvakan_vrf_v1_genesis_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e,
	0x76, 0x31, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x76, 0x65, 0x78,
	0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x72,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x02, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65,
	0x73, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x65, 0x78, 0x78, 0x76,
	0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x09, 0xc8, 0xde, 0x1f, 0x00, 0xa8, 0xe7, 0xb0, 0x2a, 0x01,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x40, 0x0a, 0x0d, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x0c, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42,
	0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65,
	0x12, 0x43, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e,
	0x2e, 0x76, 0x72, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xc7, 0x02, 0x0a, 0x09, 0x56, 0x72, 0x66, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x67, 0x65, 0x6e, 0x65,
	0x73, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x55, 0x6e, 0x69, 0x78, 0x53,
	0x65, 0x63, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x61, 0x66, 0x65, 0x74, 0x79, 0x5f, 0x6d, 0x61, 0x72,
	0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x13, 0x73, 0x61, 0x66, 0x65, 0x74, 0x79, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e,
	0x67, 0x5f, 0x67, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x47, 0x72,
	0x61, 0x63, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x3a, 0x04, 0xe8, 0xa0, 0x1f, 0x01, 0x42,
	0xaf, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61,
	0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x78, 0x78, 0x76,
	0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x72, 0x66, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x56, 0x56, 0x58, 0xaa, 0x02, 0x10, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61,
	0x6b, 0x61, 0x6e, 0x2e, 0x56, 0x72, 0x66, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x56, 0x65, 0x78,
	0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x5c, 0x56, 0x72, 0x66, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c,
	0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x5c, 0x56, 0x72, 0x66, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x56,
	0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x3a, 0x3a, 0x56, 0x72, 0x66, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vexxvakan_vrf_v1_genesis_proto_rawDescOnce sync.Once
	file_vexxvakan_vrf_v1_genesis_proto_rawDescData = file_vexxvakan_vrf_v1_genesis_proto_rawDesc
)

func file_vexxvakan_vrf_v1_genesis_proto_rawDescGZIP() []byte {
	file_vexxvakan_vrf_v1_genesis_proto_rawDescOnce.Do(func() {
		file_vexxvakan_vrf_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(file_vexxvakan_vrf_v1_genesis_proto_rawDescData)
	})
	return file_vexxvakan_vrf_v1_genesis_proto_rawDescData
}

var file_vexxvakan_vrf_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vexxvakan_vrf_v1_genesis_proto_goTypes = []interface{}{
	(*GenesisState)(nil),   // 0: vexxvakan.vrf.v1.GenesisState
	(*VrfParams)(nil),      // 1: vexxvakan.vrf.v1.VrfParams
	(*VrfBeacon)(nil),      // 2: vexxvakan.vrf.v1.VrfBeacon
	(*AllowlistEntry)(nil), // 3: vexxvakan.vrf.v1.AllowlistEntry
	(*VrfIdentity)(nil),    // 4: vexxvakan.vrf.v1.VrfIdentity
}
var file_vexxvakan_vrf_v1_genesis_proto_depIdxs = []int32{
	1, // 0: vexxvakan.vrf.v1.GenesisState.params:type_name -> vexxvakan.vrf.v1.VrfParams
	2, // 1: vexxvakan.vrf.v1.GenesisState.latest_beacon:type_name -> vexxvakan.vrf.v1.VrfBeacon
	3, // 2: vexxvakan.vrf.v1.GenesisState.committee:type_name -> vexxvakan.vrf.v1.AllowlistEntry
	4, // 3: vexxvakan.vrf.v1.GenesisState.identities:type_name -> vexxvakan.vrf.v1.VrfIdentity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vexxvakan_vrf_v1_genesis_proto_init() }
func file_vexxvakan_vrf_v1_genesis_proto_init() {
	if File_vexxvakan_vrf_v1_genesis_proto != nil {
		return
	}
	file_vexxvakan_vrf_v1_vrf_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vexxvakan_vrf_v1_genesis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenesisState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vexxvakan_vrf_v1_genesis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vexxvakan_vrf_v1_genesis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vexxvakan_vrf_v1_genesis_proto_goTypes,
		DependencyIndexes: file_vexxvakan_vrf_v1_genesis_proto_depIdxs,
		MessageInfos:      file_vexxvakan_vrf_v1_genesis_proto_msgTypes,
	}.Build()
	File_vexxvakan_vrf_v1_genesis_proto = out.File
	file_vexxvakan_vrf_v1_genesis_proto_rawDesc = nil
	file_vexxvakan_vrf_v1_genesis_proto_goTypes = nil
	file_vexxvakan_vrf_v1_genesis_proto_depIdxs = nil
}
