// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: vexxvakan/vrf/v1/tx.proto

package vrfv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_VrfEmergencyDisable_FullMethodName      = "/vexxvakan.vrf.v1.Msg/VrfEmergencyDisable"
	Msg_InitialDkg_FullMethodName               = "/vexxvakan.vrf.v1.Msg/InitialDkg"
	Msg_UpdateParams_FullMethodName             = "/vexxvakan.vrf.v1.Msg/UpdateParams"
	Msg_AddVrfCommitteeMember_FullMethodName    = "/vexxvakan.vrf.v1.Msg/AddVrfCommitteeMember"
	Msg_RemoveVrfCommitteeMember_FullMethodName = "/vexxvakan.vrf.v1.Msg/RemoveVrfCommitteeMember"
	Msg_RegisterVrfIdentity_FullMethodName      = "/vexxvakan.vrf.v1.Msg/RegisterVrfIdentity"
	Msg_ScheduleVrfReshare_FullMethodName       = "/vexxvakan.vrf.v1.Msg/ScheduleVrfReshare"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the x/vrf message service.
type MsgClient interface {
	// VrfEmergencyDisable submits an emergency disable request. The message
	// handler is intentionally light-weight; authorization and effective
	// state change are enforced by shared logic in PreBlock and the ante
	// decorator, as described in the PRD.
	VrfEmergencyDisable(ctx context.Context, in *MsgVrfEmergencyDisable, opts ...grpc.CallOption) (*MsgVrfEmergencyDisableResponse, error)
	// InitialDkg sets the initial drand chain-info required to bootstrap VRF
	// (chain_hash, public_key, period_seconds, genesis_unix_sec). On success it
	// emits an event that off-chain listeners can use to trigger DKG/bootstrap
	// workflows and refresh sidecar configuration.
	InitialDkg(ctx context.Context, in *MsgInitialDkg, opts ...grpc.CallOption) (*MsgInitialDkgResponse, error)
	// UpdateParams defines a governance operation for updating the x/vrf module
	// parameters. The authority is expected to be the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// AddVrfCommitteeMember adds or updates a VRF committee member.
	AddVrfCommitteeMember(ctx context.Context, in *MsgAddVrfCommitteeMember, opts ...grpc.CallOption) (*MsgAddVrfCommitteeMemberResponse, error)
	// RemoveVrfCommitteeMember removes a VRF committee member.
	RemoveVrfCommitteeMember(ctx context.Context, in *MsgRemoveVrfCommitteeMember, opts ...grpc.CallOption) (*MsgRemoveVrfCommitteeMemberResponse, error)
	// RegisterVrfIdentity binds a validator to its drand identity/share.
	RegisterVrfIdentity(ctx context.Context, in *MsgRegisterVrfIdentity, opts ...grpc.CallOption) (*MsgRegisterVrfIdentityResponse, error)
	// ScheduleVrfReshare bumps VrfParams.reshare_epoch to signal resharing.
	ScheduleVrfReshare(ctx context.Context, in *MsgScheduleVrfReshare, opts ...grpc.CallOption) (*MsgScheduleVrfReshareResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) VrfEmergencyDisable(ctx context.Context, in *MsgVrfEmergencyDisable, opts ...grpc.CallOption) (*MsgVrfEmergencyDisableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgVrfEmergencyDisableResponse)
	err := c.cc.Invoke(ctx, Msg_VrfEmergencyDisable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitialDkg(ctx context.Context, in *MsgInitialDkg, opts ...grpc.CallOption) (*MsgInitialDkgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgInitialDkgResponse)
	err := c.cc.Invoke(ctx, Msg_InitialDkg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddVrfCommitteeMember(ctx context.Context, in *MsgAddVrfCommitteeMember, opts ...grpc.CallOption) (*MsgAddVrfCommitteeMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAddVrfCommitteeMemberResponse)
	err := c.cc.Invoke(ctx, Msg_AddVrfCommitteeMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveVrfCommitteeMember(ctx context.Context, in *MsgRemoveVrfCommitteeMember, opts ...grpc.CallOption) (*MsgRemoveVrfCommitteeMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRemoveVrfCommitteeMemberResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveVrfCommitteeMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterVrfIdentity(ctx context.Context, in *MsgRegisterVrfIdentity, opts ...grpc.CallOption) (*MsgRegisterVrfIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterVrfIdentityResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterVrfIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ScheduleVrfReshare(ctx context.Context, in *MsgScheduleVrfReshare, opts ...grpc.CallOption) (*MsgScheduleVrfReshareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgScheduleVrfReshareResponse)
	err := c.cc.Invoke(ctx, Msg_ScheduleVrfReshare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the x/vrf message service.
type MsgServer interface {
	// VrfEmergencyDisable submits an emergency disable request. The message
	// handler is intentionally light-weight; authorization and effective
	// state change are enforced by shared logic in PreBlock and the ante
	// decorator, as described in the PRD.
	VrfEmergencyDisable(context.Context, *MsgVrfEmergencyDisable) (*MsgVrfEmergencyDisableResponse, error)
	// InitialDkg sets the initial drand chain-info required to bootstrap VRF
	// (chain_hash, public_key, period_seconds, genesis_unix_sec). On success it
	// emits an event that off-chain listeners can use to trigger DKG/bootstrap
	// workflows and refresh sidecar configuration.
	InitialDkg(context.Context, *MsgInitialDkg) (*MsgInitialDkgResponse, error)
	// UpdateParams defines a governance operation for updating the x/vrf module
	// parameters. The authority is expected to be the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// AddVrfCommitteeMember adds or updates a VRF committee member.
	AddVrfCommitteeMember(context.Context, *MsgAddVrfCommitteeMember) (*MsgAddVrfCommitteeMemberResponse, error)
	// RemoveVrfCommitteeMember removes a VRF committee member.
	RemoveVrfCommitteeMember(context.Context, *MsgRemoveVrfCommitteeMember) (*MsgRemoveVrfCommitteeMemberResponse, error)
	// RegisterVrfIdentity binds a validator to its drand identity/share.
	RegisterVrfIdentity(context.Context, *MsgRegisterVrfIdentity) (*MsgRegisterVrfIdentityResponse, error)
	// ScheduleVrfReshare bumps VrfParams.reshare_epoch to signal resharing.
	ScheduleVrfReshare(context.Context, *MsgScheduleVrfReshare) (*MsgScheduleVrfReshareResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) VrfEmergencyDisable(context.Context, *MsgVrfEmergencyDisable) (*MsgVrfEmergencyDisableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VrfEmergencyDisable not implemented")
}
func (UnimplementedMsgServer) InitialDkg(context.Context, *MsgInitialDkg) (*MsgInitialDkgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitialDkg not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) AddVrfCommitteeMember(context.Context, *MsgAddVrfCommitteeMember) (*MsgAddVrfCommitteeMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVrfCommitteeMember not implemented")
}
func (UnimplementedMsgServer) RemoveVrfCommitteeMember(context.Context, *MsgRemoveVrfCommitteeMember) (*MsgRemoveVrfCommitteeMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVrfCommitteeMember not implemented")
}
func (UnimplementedMsgServer) RegisterVrfIdentity(context.Context, *MsgRegisterVrfIdentity) (*MsgRegisterVrfIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterVrfIdentity not implemented")
}
func (UnimplementedMsgServer) ScheduleVrfReshare(context.Context, *MsgScheduleVrfReshare) (*MsgScheduleVrfReshareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleVrfReshare not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_VrfEmergencyDisable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVrfEmergencyDisable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VrfEmergencyDisable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_VrfEmergencyDisable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VrfEmergencyDisable(ctx, req.(*MsgVrfEmergencyDisable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitialDkg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitialDkg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitialDkg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_InitialDkg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitialDkg(ctx, req.(*MsgInitialDkg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddVrfCommitteeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddVrfCommitteeMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddVrfCommitteeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddVrfCommitteeMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddVrfCommitteeMember(ctx, req.(*MsgAddVrfCommitteeMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveVrfCommitteeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveVrfCommitteeMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveVrfCommitteeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveVrfCommitteeMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveVrfCommitteeMember(ctx, req.(*MsgRemoveVrfCommitteeMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterVrfIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterVrfIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterVrfIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterVrfIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterVrfIdentity(ctx, req.(*MsgRegisterVrfIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ScheduleVrfReshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgScheduleVrfReshare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ScheduleVrfReshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ScheduleVrfReshare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ScheduleVrfReshare(ctx, req.(*MsgScheduleVrfReshare))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vexxvakan.vrf.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VrfEmergencyDisable",
			Handler:    _Msg_VrfEmergencyDisable_Handler,
		},
		{
			MethodName: "InitialDkg",
			Handler:    _Msg_InitialDkg_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "AddVrfCommitteeMember",
			Handler:    _Msg_AddVrfCommitteeMember_Handler,
		},
		{
			MethodName: "RemoveVrfCommitteeMember",
			Handler:    _Msg_RemoveVrfCommitteeMember_Handler,
		},
		{
			MethodName: "RegisterVrfIdentity",
			Handler:    _Msg_RegisterVrfIdentity_Handler,
		},
		{
			MethodName: "ScheduleVrfReshare",
			Handler:    _Msg_ScheduleVrfReshare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vexxvakan/vrf/v1/tx.proto",
}
